### ISSUE TITLE
Change away from `rb-appscript`

### ISSUE THREAD

**Issue by BrendanThompson** [devondragon/jira-omnifocus#13] opened 2015-07-06 06:19 UTC
Hey there,

Is there any chance of moving away from `rb-appscript` as there are issues getting it installed onto Yosemite.

**Comment by devondragon** [comment] 2015-07-06 11:42
What issues are you running into?  I am running on Yosemite here (10.10.4) and it is working here.  I don't know the Ruby universe much, Is there something that is recommended to use instead of rb-appscript for integration with applescript?

**Comment by BrendanThompson** [comment] 2015-07-13 05:06
@devondragon i keep getting the following when i try to install `rb-appscript`, have you seen it before:

```
Building native extensions.  This could take a while...
ERROR:  Error installing rb-appscript:
	ERROR: Failed to build gem native extension.

    /usr/local/opt/ruby/bin/ruby -r ./siteconf20150713-72502-3b0x77.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/Cellar/ruby/2.2.2/bin/$(RUBY_BASE_NAME)
extconf.rb:44:in `<main>': uninitialized constant Config (NameError)

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.2.0/gems/rb-appscript-0.6.1 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0/rb-appscript-0.6.1/gem_make.out
```

**Comment by 2case** [comment] 2015-07-13 08:18
Same problem here. If used homebrew to install ruby since the system has problems on gem management

**Comment by devondragon** [comment] 2015-07-13 11:12
@2case : are you saying the issue is caused by the default ruby install but is fixed if you use homebrew?    Or the other way around?

Either way it doesn't sound like something I can fix in the code or packaging here, right?  Sorry Ruby-newbie.

**Comment by 2case** [comment] 2015-07-13 12:04
i use homebrew to manage my ruby installation, which is also the system i have the gem installation problem with. i didn't (and even won't) test it with the system ruby installation since the system ruby have general gem management problems because of the system/user rights.

As you can read in the http://appscript.sourceforge.net/status.html status message, the library is no longer developed or supported. There are missing libraries on 10.10 for some cocoa things so the rb-appscript build fail. Seems that on your system are old libs installed.

i tried to find the mkmf.log to check what exactly is the build problem, but this will seems deleted during the failure make handling...

**Comment by devondragon** [comment] 2015-07-13 12:11
Hmm that is odd.  I did a clean install of Yosemite on a new laptop so I shouldn't have any old libs on this computer at all.  
There doesn't seem to be any easy path away from rb-appscript.. it looks like it would involve a lot of re-coding.  If anything perhaps I could write the whole thing in applescript and ditch ruby....  hmmm.

**Comment by andrewguy9** [comment] 2015-07-13 17:16
In Yosemite onwards they expose Javascript bindings for the old apple script interfaces. I haven't tried it yet, but maybe thats a good alternative to AppleScript.

**Comment by BrendanThompson** [comment] 2015-07-14 00:14
Okay peeps, i spent a little time this morning modifying `rb-apscript`, i have created a forked gem called `rb-scpt` which can be found [here](https://github.com/BrendanThompson/rb-scpt), this now allows for it to be built cleaning on newer versions of Ruby.

It looks as though the issue was that in around Ruby 1.8 they changed from `config` to `rbconfig`, also it moved from the implicit requirement of `config` to the explicit requirement of `rbconfig` in the require statements.

Currently the gem isn't published and is just sitting in my GH. If you think it fits the brief let me know and i will publish it.

---

As per what @andrewguy9 is saying, you could indeed go for a more __jxa__ orientated way :).

**Comment by BrendanThompson** [comment] 2015-07-14 06:12
Okay, I have [published the gem](https://rubygems.org/gems/rb-scpt) :). Although am having some issues with the script, it seems to be erroring on the `config` array, if it's empty.

**Comment by devondragon** [comment] 2015-12-17 21:23
This has been fixed with PR 20 https://github.com/devondragon/jira-omnifocus/pull/20 from @grahl !

**Closed by devondragon** 2015-12-17 21:23 UTC
